server:
  port: 9000
spring:
  profiles:
    active: product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/photo
    username: postgres
    password: root
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false